[Rule]
DOMAIN-KEYWORD,whatshub.top,DIRECT
DOMAIN-SUFFIX,pasyun.com,DIRECT
DOMAIN-SUFFIX,cloudflare.com,DIRECT
DOMAIN-SUFFIX,ip.sb,🚀 节点选择
RULE-SET,https://whatshub.top/rule/YouTube.list,🇵🇱 波兰vmess
RULE-SET,https://whatshub.top/rule/Telegram.list,🇺🇸 美国节点
RULE-SET,https://whatshub.top/rule/ai.list,🇺🇸 美国PSY
RULE-SET,https://whatshub.top/rule/Twitter.list,🇺🇸 美国PSY
RULE-SET,https://whatshub.top/rule/Twitch.list,🇺🇸 美国PSY
